// <auto-generated />
using System;
using EldredBrown.ProFootball.NETCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EldredBrown.ProFootball.NETCore.Data.Migrations
{
    [DbContext(typeof(ProFootballDbContext))]
    [Migration("20191114075156_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EldredBrown.ProFootball.NETCore.Data.Entities.League", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FirstSeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("LastSeasonId")
                        .HasColumnType("int");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("ID");

                    b.HasAlternateKey("LongName")
                        .HasName("AlternateKey_LongName");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstSeasonId = 1920,
                            LastSeasonId = 1921,
                            LongName = "American Professional Football Association",
                            ShortName = "APFA"
                        },
                        new
                        {
                            ID = 2,
                            FirstSeasonId = 1922,
                            LongName = "National Football League",
                            ShortName = "NFL"
                        },
                        new
                        {
                            ID = 3,
                            FirstSeasonId = 1946,
                            LastSeasonId = 1949,
                            LongName = "All-America Football Conference",
                            ShortName = "AAFC"
                        },
                        new
                        {
                            ID = 4,
                            FirstSeasonId = 1960,
                            LastSeasonId = 1969,
                            LongName = "American Football League",
                            ShortName = "AFL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
